# Generated by Django 4.2.13 on 2026-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
